"""SQLAlchemy ORM model for build jobs."""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


def _uuid() -> str:
    return str(uuid.uuid4())


class BuildJob(Base):
    """Persisted record of an image build job."""

    __tablename__ = "build_jobs"

    id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=_uuid,
    )
    # server_default covers DB-level default; default= covers INSERT via ORM.
    # We also need a Python-level sentinel so callers don't have to supply it.
    # SQLAlchemy 2.x Mapped columns support __init_subclass__ kwarg defaults
    # via the `__init__` generated by the mapper — but only when the default
    # is set on the column via `default=`.  The column default IS evaluated
    # before flush, so accessing .status after construction (before flush) can
    # return None unless we explicitly call __init__ with the right default.
    # Workaround: __init__ override to supply the default.
    status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        server_default="pending",
    )
    source_type: Mapped[str] = mapped_column(String, nullable=False)
    runtime_type: Mapped[str] = mapped_column(String, nullable=False)
    image_ref: Mapped[str] = mapped_column(String, nullable=False)
    k8s_job_name: Mapped[str | None] = mapped_column(String, nullable=True)
    logs_url: Mapped[str | None] = mapped_column(String, nullable=True)
    error: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __init__(
        self,
        *,
        source_type: str,
        runtime_type: str,
        image_ref: str,
        id: str | None = None,
        status: str = "pending",
        k8s_job_name: str | None = None,
        logs_url: str | None = None,
        error: str | None = None,
        created_at: datetime | None = None,
        updated_at: datetime | None = None,
    ) -> None:
        self.id = id if id is not None else _uuid()
        self.status = status
        self.source_type = source_type
        self.runtime_type = runtime_type
        self.image_ref = image_ref
        self.k8s_job_name = k8s_job_name
        self.logs_url = logs_url
        self.error = error
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
